spring.profiles.active=development

springdoc.api-docs.path=/smart-seaman-swagger
spring.main.allow-circular-references=true
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

## DataSource
smart.seaman.datasource.driver=com.mysql.cj.jdbc.Driver

#smart.seaman.datasource.url=jdbc:mysql://127.0.0.1:3306/seaman?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=round
#smart.seaman.datasource.username=root
#smart.seaman.datasource.password=

#### PROD #####
smart.seaman.datasource.url=${SMART_SEAMAN_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/seaman?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=round}
smart.seaman.datasource.username=${SMART_SEAMAN_DATASOURCE_USERNAME:root}
smart.seaman.datasource.password=${SMART_SEAMAN_DATASOURCE_PASSWORD:}

#### DEV #####
#smart.seaman.datasource.url=${SMART_SEAMAN_DEV_DATASOURCE_URL:}
#smart.seaman.datasource.username=${SMART_SEAMAN_DEV_DATASOURCE_USERNAME:}
#smart.seaman.datasource.password=${SMART_SEAMAN_DEV_DATASOURCE_PASSWORD:}

## Upload file to S3
object.store.endpoint=${OBJECT_STORE_ENDPOINT:}
object.store.key=${OBJECT_STORE_KEY:}
object.store.secret=${OBJECT_STORE_SECRET:}
object.store.region=${OBJECT_STORE_REGION:Singapore}
object.store.bucket=${OBJECT_STORE_BUCKET:smart-seaman-bucket}
object.store.path.root=documents
object.store.path.template=${object.store.path.root}/%s/certs/%s
object.store.path.documents.download=document_download
object.store.path.news=news
object.store.path.profile.picture=profile_picture
object.store.path.banner=banner
object.store.path.profiles.images=profiles/images
object.store.path.voucher=voucher
object.store.path.voucher.qr=voucher/qr


## HikariCP settings
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

## Encrypt && Decrypt key
encrypt.cert.key=${ENCRYPT_CERT_KEY:change-me}
jwt.secret=${JWT_SECRET:change-me}

## Fcm
fcm.url=https://fcm.googleapis.com/fcm/send
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:firebase-service-account.json}

#PROD
fcm.auth=${FCM_AUTH:}

#Dev
#fcm.auth=${FCM_DEV_AUTH:}
